version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      cluster.name: elasticsearch
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: "curl -f http://localhost:9200 || exit 1"
      start_period: 1m

#  elastic-boot:
#    container_name: elastic-boot-container
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - "8090:8090"
#    depends_on: # Start the depends_on first
#      - elasticsearch
#    healthcheck:
#      test: "wget --quiet --tries=1 --spider http://localhost:8090 || exit 1"
#    restart: unless-stopped

